version: 0.0.1.{build}

environment:
   CTEST_OUTPUT_ON_FAILURE: 1
   matrix:
      - BUILD:  msvc
        CONFIG: Debug

before_build:
   - git submodule update --init

build_script:
   - waf --check-cxx-compiler=msvc --msvc_version="msvc 12.0" configure build --notest"

test_script:
   - waf build --alltests
